--- #Bootstrap server
- hosts: aws_serv
  become: yes
  tasks:
  - name: updating ec2
    apt:
      update_cache: yes
  - name: install apache2
    apt:
      name: apache2
      state: latest
      update_cache: yes
  - name: delete index.html file
    ansible.builtin.file:
      name: /var/www/html/index.html
      state: absent
  - name: create index.html file
    ansible.builtin.file:
      name: /var/www/html/index.html
      state: touch
  - name: add web content
    lineinfile:
      line: "algo de texto html"
      path: /var/www/html/index.html
  - name: start server
    service:
      name: apache2
      state: started

